apiVersion: apps/v1
kind: Deployment
metadata:
  name: visittemple
spec:
  selector:
    matchLabels:
      app: visittemple
  template:
    metadata:
      labels:
        app: visittemple
    spec:
      containers:
      - name: visittemple
        image: us-central1-docker.pkg.dev/devops-353009/devops-docker/visittemple:0.0.2-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
